nome = input("Informe o seu nome: ")
sobrenome = input("Qual o seu sobrenome: ")
print(f'Meu nome é {nome} {sobrenome}')
print(nome, sobrenome)
print(nome, sobrenome, end="...\n")
print(nome, sobrenome, sep="#")
